Repository red-hat-storage/ocs-client-operator, pull requests merged in 2023-11, with the labels that each got.

#38 Bug 2247737: add APIs to scheme, role and role binding to bundle
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  service/status-report/main.go
Labels: size/S, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug, approved

#39 Bug 2247748: A storage-client CronJob create too many jobs and pods causing maxPod limit to be reached
  controllers/storageclient_controller.go
Labels: size/S, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug

#40 Bug 2247735: Adding toleration to schedule CSI pods on master nodes
  pkg/csi/cephfsdaemonset.go
  pkg/csi/rbddaemonset.go
  pkg/utils/k8sutils.go
  pkg/utils/placements.go
Labels: size/M, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
