Repository red-hat-storage/ocs-client-operator, pull requests merged in 2023-02, with the labels that each got.

#13 cleanup: replace ODF with OCO
  Makefile
  hack/make-bundle-vars.mk
Labels: size/XS

#12 Allow multiple storageclients per namespace
  controllers/clusterversion_controller.go
  controllers/storageclient_controller.go
Labels: size/M

#15 bundle: enable bundle generation for fusion
  Makefile
  config/manifests/fusion/kustomization.yaml
  hack/make-bundle-vars.mk
Labels: size/M

#16 Fix problems found in recent testing
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/storageclassclaim_controller.go
  controllers/storageclient_controller.go
  main.go
Labels: size/L

#14 create monitoring prometheus rules
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
  controllers/pvc-rules.yaml
  go.mod
  go.sum
  hack/make-bundle-vars.mk
  main.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L

#17 Fix bugs found in testing
  Makefile
  api/v1alpha1/storageclassclaim_types.go
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/status-reporter-clusterrole.yaml
  config/rbac/status-reporter-clusterrole_binding.yaml
  controllers/storageclassclaim_controller.go
  controllers/storageclient_controller.go
  main.go
  pkg/csi/csi.go
  pkg/csi/encryptionconfigmap.go
  pkg/csi/monconfigmap.go
  service/status-report/main.go
Labels: size/L
