Repository red-hat-storage/ocs-client-operator, pull requests merged in 2023-03, with the labels that each got.

#19 csi: use openshift registry to pull ocp images
  images.yaml
Labels: size/S

#20 bundle: add missing CRD to bundle
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclassclaims.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  config/default/kustomization.yaml
Labels: size/L

#21 Use configmap for the sidecar images mapping
  Dockerfile
  bundle/manifests/ocs-client-operator-csi-images_v1_configmap.yaml
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manager/csi-images.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  controllers/clusterversion_controller.go
  controllers/storageclient_controller.go
  images.yaml
  pkg/csi/csi.go
Labels: size/M

#22 makefile: add make target and variables to specify CSI images
  Makefile
  hack/gen-csi-images-manifest.sh
  hack/make-bundle-vars.mk
Labels: size/M

#24 Add GitHub Action for testing changes to CSI images
  .github/workflows/verify-generated.yaml
  Makefile
  hack/gen-csi-images-manifest.sh
  hack/make-bundle-vars.mk
Labels: size/M

#23 Fix bugs found in migration of ODF to ocs-client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/storageclassclaim_controller.go
Labels: size/S, lgtm
