Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-06, with the labels that each got.

#159 controllers: ensure csi-addons sub channel matches ocs-client-op channel
  controllers/operatorconfigmap_controller.go
Labels: size/L, lgtm, approved

#170 add annotation to csv to make storageclaim internal
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
Labels: size/XS, lgtm, approved

#171 Syncing latest changes from main for ocs-client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/status-reporter-clusterrole.yaml
  controllers/operatorconfigmap_controller.go
Labels: size/L, lgtm, approved

#152 BUG 2276565: match csi-addons subscription channel to ocs-client-operator
  .golangci.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
Labels: size/M, lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#173 BUG 2276565: controllers: fixed typo subscription to subscriptions
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
Labels: size/S, lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high
