Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-08, with the labels that each got.

#195 Syncing latest changes from main for ocs-client-operator
  .github/workflows/verify-generated.yaml
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cmd/main.go
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  hack/go-build.sh
  hack/godeps-verify.sh
  internal/controller/generate.go
  internal/controller/operatorconfigmap_controller.go
  internal/controller/pvc-rules.yaml
  internal/controller/sliceutils.go
  internal/controller/sliceutils_test.go
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  internal/controller/suite_test.go
  pkg/utils/k8sutils.go
  service/deployment-guard/main.go
Labels: size/L, lgtm, approved

#197 Bug 2300289: [release-4.16] init container to decide allowing reconciliation of manager
  Dockerfile
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/operatorconfigmap_controller.go
  hack/go-build.sh
  service/deployment-guard/main.go
Labels: size/L, lgtm, bugzilla/severity-urgent, bugzilla/valid-bug, approved

#175 replace reconcililation of ceph csi deployments with ceph-csi-operator resources
  Makefile
  bundle/manifests/csi-images-v4.15
  bundle/manifests/csi-images-v4.16
  bundle/manifests/csi-images-v4.17
  bundle/manifests/ocs-client-operator-csi-images_v1_configmap.yaml
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  cmd/main.go
  config/manager/csi-images.yaml
  config/metadata/dependencies.yaml
  config/rbac/role.yaml
  config/rbac/status-reporter-role.yaml
  go.mod
  go.sum
  hack/create-csi-images-manifest.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
  internal/controller/operatorconfigmap_controller_test.go
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  pkg/csi/monconfigmap.go
  pkg/templates/csi.go
  pkg/utils/csi.go
  pkg/utils/k8sutils.go
  service/status-report/main.go
  vendor/github.com/ceph/ceph-csi-operator/api/LICENSE
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/cephconnection_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/clientprofile_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/clientprofilemapping_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/driver_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/operatorconfig_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/evanphx/json-patch/.gitignore
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/k8s.io/client-go/testing/interface.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: size/XXL, lgtm, approved

#203 controllers: deploy CSI if opted in
  pkg/utils/csi.go
Labels: lgtm, approved

#206 hack: fix attacher env var typo
  hack/create-csi-images-manifest.sh
Labels: size/XS, lgtm, approved

#208 controllers: wait for 90 sec before checking StorageCluster CRD
  service/deployment-guard/main.go
Labels: size/S, lgtm, approved

#213 csi: change SA name in csi SCCs
  pkg/templates/csi.go
Labels: size/XS, lgtm, approved, do-not-merge/hold

#215 makefile: update csi-addons bundle version from 0.8.0 to 0.9.0
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/make-bundle-vars.mk
Labels: size/S, lgtm, approved

#212 controllers: configure log rotater spec in csi-op operatorconfig
  pkg/templates/csi.go
Labels: size/S, lgtm, approved

#218 makefile: update csi-addons bundle version from 0.9.0 to 0.9.1
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/make-bundle-vars.mk
Labels: size/S, lgtm, approved
