Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-05, with the labels that each got.

#143 Refactors status Setters and restricts RBAC
  config/rbac/status-reporter-clusterrole.yaml
  service/status-report/main.go
Labels: size/L, lgtm, approved

#151 Setting basedomain as cluster name
  config/rbac/status-reporter-clusterrole.yaml
  service/status-report/main.go
Labels: size/M, lgtm, approved

#156 Bug 2278593: [release-4.16] Setting basedomain as cluster name
  config/rbac/status-reporter-clusterrole.yaml
  service/status-report/main.go
Labels: size/L, lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#160 Syncing latest changes from main for ocs-client-operator
  config/rbac/status-reporter-clusterrole.yaml
  service/status-report/main.go
Labels: size/M, lgtm, approved

#139 Bug 2274675: [release-4.14] csi: remove cpu & memory limits from sidecars
  .github/workflows/golangci-lint.yaml
  pkg/csi/cephfsdaemonset.go
  pkg/csi/cephfsdeployment.go
  pkg/csi/rbddaemonset.go
  pkg/csi/rbddeployment.go
  pkg/templates/csisidecars.go
Labels: size/M, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug

#150 Updated comment description from storageclassclaim to storageclaim
  controllers/operatorconfigmap_controller.go
Labels: size/XS, lgtm, approved

#158 bundle: update csv with info required for release
  bundle.Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  hack/make-tools.mk
Labels: size/M, lgtm, approved

#165 bundle: update missing and incorrect rbac resources
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/status-reporter-clusterrole.yaml
Labels: size/S, lgtm, approved

#167 Syncing latest changes from main for ocs-client-operator
  LICENSE
  bundle.Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  controllers/operatorconfigmap_controller.go
  hack/make-tools.mk
Labels: size/L, lgtm, approved
