Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-09, with the labels that each got.

#161 bundle: add noobaa-operator dependency
  bundle/metadata/dependencies.yaml
  config/manager/manager.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
  pkg/utils/subscription.go
Labels: size/M, lgtm, approved

#176 Add support for noobaa on client clusters
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/storageclient_controller.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/LICENSE
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/register.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1/doc.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1/objectbucket_types.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1/register.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner/api/domain.go
  vendor/github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner/api/provisioner.go
  vendor/github.com/noobaa/noobaa-operator/v5/LICENSE
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/addtoscheme_noobaa_v1alpha1.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/apis.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/backingstore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/cosi_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/doc.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaa_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/obc_types.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/register.go
  vendor/github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/container-object-storage-interface-api/LICENSE
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/bucket_info.go
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/register.go
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1/doc.go
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1/register.go
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1/types.go
  vendor/sigs.k8s.io/container-object-storage-interface-api/apis/objectstorage/v1alpha1/zz_generated.deepcopy.go
Labels: size/XL, lgtm, approved

#219 Disable noobaa management on client for dev preview
  internal/controller/operatorconfigmap_controller.go
Labels: size/XS, lgtm, approved

#224 bundle: add capabilities to csv
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
Labels: size/XS, lgtm, approved

#227 controller: update storageclient connection fail log
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  service/status-report/main.go
Labels: size/XS, lgtm, approved

#228 bundle: add default toleration to operators and cronjob
  config/console/console_init.yaml
  config/manager/manager.yaml
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#229 bundle: chore - run `make bundle`
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
Labels: size/S, lgtm, approved

#237 controllers: default log verbosity for csi containers should be 5
  pkg/templates/csi.go
Labels: size/XS, lgtm, approved

#236 Syncing latest changes from main for ocs-client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/manager/manager.yaml
  internal/controller/storageclient_controller.go
Labels: size/M, lgtm, approved

#241 controllers: Fix secret creation in storageclient controller
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#246 controllers: Fix unmarshalling of secret in storageclientcontroller
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#199 hack: update csv timestamp only when there are changes in bundle
  .github/workflows/verify-generated.yaml
  Makefile
  hack/update-csv-timestamp.sh
Labels: size/S, lgtm, approved
