Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-07, with the labels that each got.

#153 RHSTOR-5879: Annotate storageclasses for Reclaimspace by ocs-client-o…
  controllers/storageclaim_controller.go
Labels: size/XS, lgtm, approved

#186 bundle: update build tools and versions
  Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclaims.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  config/crd/bases/ocs.openshift.io_storageclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclients.yaml
  config/rbac/role.yaml
  controllers/storageclaim_controller.go
  go.mod
  hack/make-bundle-vars.mk
  hack/make-project-vars.mk
  hack/make-tools.mk
Labels: size/M, lgtm, approved

#188 ci: use golangci-lint version from makefile
  .github/workflows/golangci-lint.yaml
  hack/build.env
  hack/make-project-vars.mk
Labels: size/S, lgtm, approved

#162 action: update docker-push action for pushing images on demand
  .github/workflows/docker-push.yaml
Labels: size/S, lgtm, approved

#182 Changes to read quota and create
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  controllers/storageclaim_controller.go
  controllers/storageclient_controller.go
  main.go
  pkg/utils/k8sutils.go
  vendor/github.com/openshift/api/quota/v1/Makefile
  vendor/github.com/openshift/api/quota/v1/doc.go
  vendor/github.com/openshift/api/quota/v1/generated.pb.go
  vendor/github.com/openshift/api/quota/v1/generated.proto
  vendor/github.com/openshift/api/quota/v1/legacy.go
  vendor/github.com/openshift/api/quota/v1/register.go
  vendor/github.com/openshift/api/quota/v1/stable.clusterresourcequota.testsuite.yaml
  vendor/github.com/openshift/api/quota/v1/types.go
  vendor/github.com/openshift/api/quota/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/quota/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/quota/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#193 action: migrate from go/v3 to go/v4
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  cmd/main.go
  hack/go-build.sh
  internal/controller/generate.go
  internal/controller/operatorconfigmap_controller.go
  internal/controller/pvc-rules.yaml
  internal/controller/sliceutils.go
  internal/controller/sliceutils_test.go
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  internal/controller/suite_test.go
Labels: size/M, lgtm, approved

#194 hack: add verification of go deps in gh action
  .github/workflows/verify-generated.yaml
  Makefile
  hack/godeps-verify.sh
Labels: size/M, lgtm, approved

#183 RHSTOR-5883: Annotate RBD storageclasses for EncryptionKeyRotation
  internal/controller/storageclaim_controller.go
  pkg/utils/k8sutils.go
Labels: size/XS, lgtm, approved

#196 init container to decide allowing reconciliation of manager
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  hack/go-build.sh
  internal/controller/operatorconfigmap_controller.go
  service/deployment-guard/main.go
Labels: size/L, lgtm, approved

#198 controllers: remove redundant code in init container
  service/deployment-guard/main.go
Labels: size/XS, lgtm, approved
