Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-03, with the labels that each got.

#93 csi: remove cpu & memory limits from sidecars
  pkg/csi/cephfsdaemonset.go
  pkg/csi/cephfsdeployment.go
  pkg/csi/rbddaemonset.go
  pkg/csi/rbddeployment.go
  pkg/templates/csisidecars.go
Labels: size/M, lgtm, approved

#79 Change ownership logic to enforce after the DeepCopy
  controllers/clusterversion_controller.go
Labels: size/S, lgtm, approved

#96 csi: update sidecars to latest release
  config/manager/csi-images.yaml
  hack/make-bundle-vars.mk
Labels: size/M, lgtm, approved

#99 Bug 2267712: [release-4.15] add description to client operator csv
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  controllers/clusterversion_controller.go
Labels: size/XS, lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#97 ci: use action.yaml for setting up go during CI
  action.yaml
Labels: size/S, lgtm, approved

#87 controllers: use annotations for claims and client mapping
  controllers/storageclassclaim_controller.go
  controllers/storageclient_controller.go
Labels: size/M, lgtm, approved

#95 Syncing latest changes from main for ocs-client-operator
  OWNERS
  api/v1alpha1/storageclassclaim_types.go
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclients.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
  hack/make-bundle-vars.mk
  hack/make-tools.mk
  pkg/csi/csi.go
  pkg/csi/rbddeployment.go
  pkg/templates/csisidecars.go
  pkg/templates/defaults.go
Labels: size/L, lgtm, approved

#111 update ocs-operator dependency for updated proto definitions
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/provider.pb.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#107 Refactor CSI package code to reduce memory, GC overhead, and "order of operations" considerations
  controllers/clusterversion_controller.go
  pkg/csi/cephfsdaemonset.go
  pkg/csi/cephfsdeployment.go
  pkg/csi/rbddaemonset.go
  pkg/csi/rbddeployment.go
  pkg/csi/scc.go
  pkg/templates/csidriver.go
  pkg/templates/csisidecars.go
Labels: size/XXL, lgtm, approved

#113 controllers: deploy csi correctly by adding labels
  pkg/csi/cephfsdaemonset.go
  pkg/csi/cephfsdeployment.go
  pkg/csi/rbddaemonset.go
  pkg/csi/rbddeployment.go
  pkg/utils/k8sutils.go
Labels: size/M, lgtm, approved

#89 store desired subscription channel as annotation on storageclient CR
  controllers/storageclassclaim_controller.go
  pkg/utils/k8sutils.go
  service/status-report/main.go
Labels: size/M, lgtm, approved

#88 storageclassclaim: check for and configure RADOS namespace
  controllers/storageclassclaim_controller.go
  pkg/csi/monconfigmap.go
Labels: size/M, lgtm, approved

#119 deploy CSI conditionally if client is running in provider mode or standalone
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
  main.go
Labels: size/L, lgtm, approved

#115 implement webhook for validating ocs-client-operator subscription channel
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/webhook_service.yaml
  config/rbac/role.yaml
  config/rbac/status-reporter-clusterrole.yaml
  controllers/clusterversion_controller.go
  controllers/storageclient_controller.go
  main.go
  pkg/templates/validatingwebhook.go
  pkg/utils/k8sutils.go
  pkg/webhook/subscription.go
  service/status-report/main.go
Labels: size/L, lgtm, approved

#121 RDR: setting client info
  go.mod
  go.sum
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/storageclient.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#118 create default storageclaim corresponding to storageclient
  controllers/storageclient_controller.go
Labels: size/L, lgtm, approved
