Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-11, with the labels that each got.

#254 controllers: send storage utilization ratio in heartbeat
  go.mod
  go.sum
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#266 Labels `VolumeSnapshotClass`
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  cmd/main.go
  go.mod
  go.sum
  internal/controller/storageclaim_controller.go
  pkg/utils/k8sutils.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#269 bundle: update versions
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/make-bundle-vars.mk
Labels: size/S, lgtm, approved, do-not-merge/hold

#268 api: adding role and set correct name to get CRQ
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/status-reporter-clusterrole.yaml
  internal/controller/storageclient_controller.go
  pkg/utils/k8sutils.go
  service/status-report/main.go
Labels: size/S, lgtm, approved

#270 controllers: send storageclient uid from status reporter
  go.mod
  go.sum
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider_grpc.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#105 csi: enable csi-omap based on key in operator config
  bundle/manifests/ocs-client-operator-config_v1_configmap.yaml
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  internal/controller/operatorconfigmap_controller.go
Labels: size/S, lgtm, approved

#265 controllers: create clientprofilemapping required for DR
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#272 update ceph csi deps
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/storageclient_controller.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/clientprofilemapping_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/driver_types.go
  vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#276 controllers: create vrc sent by the provider
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/storageclaim_controller.go
  pkg/utils/k8sutils.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/LICENSE
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/groupversion_info.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplication_types.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationclass_types.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplication_types.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/volumereplicationclass_types.go
  vendor/github.com/csi-addons/kubernetes-csi-addons/api/replication.storage/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/k8s.io/api/resource/v1alpha3/generated.pb.go
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#277 controllers: add missing owner on sc and vsc
  internal/controller/storageclaim_controller.go
Labels: size/XS, lgtm, approved

#278 controllers: set the vrc name to what we get from provider
  internal/controller/storageclaim_controller.go
Labels: size/XS, lgtm, approved

#264 controllers: new controller for maintenance mode
  api/v1alpha1/storageclient_types.go
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  cmd/main.go
  config/crd/bases/ocs.openshift.io_storageclients.yaml
  config/rbac/role.yaml
  internal/controller/maintenancemode_controller.go
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  pkg/utils/k8sutils.go
  pkg/utils/predicates.go
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclient_types.go
Labels: size/L, lgtm, approved

#281 api: make inMaintenanceMode optional
  api/v1alpha1/storageclient_types.go
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  config/crd/bases/ocs.openshift.io_storageclients.yaml
Labels: size/XS, lgtm, approved

#284 controllers: fix typo for volumereplicationclasses
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/storageclaim_controller.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclient_types.go
Labels: size/XS, lgtm, approved
