Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-02, with the labels that each got.

#66 remove non-standalone annotation
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
Labels: size/XS, lgtm, approved

#65 controllers: pick next best version of csi images
  controllers/clusterversion_controller.go
  pkg/csi/csi.go
Labels: size/M, lgtm, approved

#74 Bug 2263312: Backport fusion hci phase 2 related changes to 4.14 branch
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clusterversion_controller.go
  controllers/storageclassclaim_controller.go
  controllers/storageclient_controller.go
  go.mod
  go.sum
  main.go
  pkg/console/console.go
  pkg/csi/cephfsdaemonset.go
  pkg/csi/cephfsdeployment.go
  pkg/csi/csi.go
  pkg/csi/rbddaemonset.go
  pkg/csi/rbddeployment.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/clientstatus/status.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/storageclient.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/storageclient_status.go
  vendor/modules.txt
Labels: size/L, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug, approved

#76 controllers: use blank identifier for unused param
  controllers/clusterversion_controller.go
Labels: size/XS, lgtm, approved

#75 ci: add leelavg to OWNERS files
  OWNERS
Labels: size/XS, lgtm, approved

#72 makefile: update controller gen version
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclients.yaml
  config/rbac/role.yaml
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: size/S, lgtm, approved

#73 api: make storageClassClaim immutable
  api/v1alpha1/storageclassclaim_types.go
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
Labels: size/XS, lgtm, approved

#84 csi: add csi-addon sidecar to the rbd provisioner deployment
  pkg/csi/rbddeployment.go
  pkg/templates/csisidecars.go
  pkg/templates/defaults.go
Labels: size/M, lgtm, approved
