Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-04, with the labels that each got.

#110 make development possible on different os/arch
  .gitignore
  .golangci.yaml
  Dockerfile
  Makefile
  bundle/manifests/ocs-client-operator-csi-images_v1_configmap.yaml
  bundle/manifests/ocs.openshift.io_storageclassclaims.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/go-test-setup.sh
  hack/go-test.sh
  hack/make-bundle-vars.mk
  hack/make-project-vars.mk
  hack/make-tools.mk
Labels: size/L, lgtm, approved

#64 Redesign for ClusterVersion controller into OperatorConfigMap controller
  controllers/operatorconfigmap_controller.go
  main.go
  pkg/utils/deployment.go
Labels: size/L, lgtm, approved

#120 implement ocs-client-operator auto upgrade
  controllers/operatorconfigmap_controller.go
Labels: size/M, lgtm, approved

#129 Fix placeholder kube-rbac-proxy image to respect supplied image during build time
  config/default/manager_auth_proxy_patch.yaml
Labels: size/XS, lgtm, approved

#132 update csi-addons dependency from 0.5.0 to 0.8.0
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/make-bundle-vars.mk
Labels: size/XS, lgtm, approved

#80 Handle csi drivers and scc deletion
  controllers/operatorconfigmap_controller.go
Labels: size/L, lgtm, approved

#127 Setting the cluster's name
  service/status-report/main.go
Labels: size/M, lgtm, approved

#81 Add a deletion safegaurd mechanism for csi resources
  controllers/operatorconfigmap_controller.go
Labels: size/XS, lgtm, approved

#140 reconcile webhook service and deletion of webhook
  config/manager/webhook_service.yaml
  controllers/operatorconfigmap_controller.go
  pkg/templates/webhookservice.go
Labels: size/M, lgtm, approved

#133 make storageclient api to clusterscope resource
  api/v1alpha1/storageclaim_types.go
  api/v1alpha1/storageclient_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ocs.openshift.io_storageclaims.yaml
  bundle/manifests/ocs.openshift.io_storageclients.yaml
  config/crd/bases/ocs.openshift.io_storageclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclients.yaml
  controllers/storageclaim_controller.go
  controllers/storageclassclaim_migration_controller.go
  controllers/storageclient_controller.go
  pkg/utils/k8sutils.go
  service/status-report/main.go
Labels: size/XL, lgtm, approved

#136 rename storageclassclaim to storageclaim in gRPC methods
  controllers/storageclaim_controller.go
  go.mod
  go.sum
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/provider_grpc.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/pb/storageclient.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#146 api: remove storageclassclaim api & migration controller
  PROJECT
  api/v1alpha1/storageclaim_types.go
  api/v1alpha1/storageclassclaim_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  controllers/storageclassclaim_migration_controller.go
  main.go
Labels: size/L, lgtm, approved

#145 make value of storageclaim type case insensitive and consistent
  api/v1alpha1/storageclaim_types.go
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclaims.yaml
  bundle/manifests/ocs.openshift.io_storageclassclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclaims.yaml
  config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageclassclaims.yaml
  config/crd/patches/webhook_in_storageclassclaims.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/storageclassclaim_editor_role.yaml
  config/rbac/storageclassclaim_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1alpha1_storageclassclaim.yaml
  controllers/storageclaim_controller.go
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/v4/services/provider/client/client.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#148 controllers: define claimType before getting storageclass
  controllers/storageclaim_controller.go
Labels: size/XS, lgtm, approved
