Repository red-hat-storage/ocs-client-operator, pull requests merged in 2024-10, with the labels that each got.

#248 use provider/api module as the dependency in place of whole ocs-operator
  go.mod
  go.sum
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  service/status-report/main.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/LICENSE
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/interfaces/interfaces.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider_grpc.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/storageclient.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#251 controllers: add ocs default toleration to csi driver spec
  pkg/templates/csi.go
Labels: size/S, lgtm, approved

#256 hack: fix the entrypoint script
  hack/entrypoint.sh
Labels: size/XS, lgtm, approved

#257 controllers: fix available crd
  Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  internal/controller/storageclaim_controller.go
  pkg/utils/predicates.go
Labels: size/M, lgtm, approved

#258 Syncing latest changes from main for ocs-client-operator
  Dockerfile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  hack/entrypoint.sh
  internal/controller/storageclaim_controller.go
  pkg/utils/predicates.go
Labels: size/M, lgtm, approved

#262 bundle: remove redundant RBAC and Makefile target
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/csi_cephfs_plugin_clusterrole.yaml
  config/rbac/csi_cephfs_plugin_clusterrole_binding.yaml
  config/rbac/csi_cephfs_plugin_service_account.yaml
  config/rbac/csi_cephfs_provisioner_clusterrole.yaml
  config/rbac/csi_cephfs_provisioner_clusterrole_binding.yaml
  config/rbac/csi_cephfs_provisioner_role.yaml
  config/rbac/csi_cephfs_provisioner_role_binding.yaml
  config/rbac/csi_cephfs_provisioner_service_account.yaml
  config/rbac/csi_rbd_plugin_clusterrole.yaml
  config/rbac/csi_rbd_plugin_clusterrole_binding.yaml
  config/rbac/csi_rbd_plugin_role.yaml
  config/rbac/csi_rbd_plugin_role_binding.yaml
  config/rbac/csi_rbd_plugin_service_account.yaml
  config/rbac/csi_rbd_provisioner_clusterrole.yaml
  config/rbac/csi_rbd_provisioner_clusterrole_binding.yaml
  config/rbac/csi_rbd_provisioner_role.yaml
  config/rbac/csi_rbd_provisioner_role_binding.yaml
  config/rbac/csi_rbd_provisioner_service_account.yaml
  config/rbac/kustomization.yaml
Labels: size/XL, lgtm, approved

#263 Syncing latest changes from main for ocs-client-operator
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/csi_cephfs_plugin_clusterrole.yaml
  config/rbac/csi_cephfs_plugin_clusterrole_binding.yaml
  config/rbac/csi_cephfs_plugin_service_account.yaml
  config/rbac/csi_cephfs_provisioner_clusterrole.yaml
  config/rbac/csi_cephfs_provisioner_clusterrole_binding.yaml
  config/rbac/csi_cephfs_provisioner_role.yaml
  config/rbac/csi_cephfs_provisioner_role_binding.yaml
  config/rbac/csi_cephfs_provisioner_service_account.yaml
  config/rbac/csi_rbd_plugin_clusterrole.yaml
  config/rbac/csi_rbd_plugin_clusterrole_binding.yaml
  config/rbac/csi_rbd_plugin_role.yaml
  config/rbac/csi_rbd_plugin_role_binding.yaml
  config/rbac/csi_rbd_plugin_service_account.yaml
  config/rbac/csi_rbd_provisioner_clusterrole.yaml
  config/rbac/csi_rbd_provisioner_clusterrole_binding.yaml
  config/rbac/csi_rbd_provisioner_role.yaml
  config/rbac/csi_rbd_provisioner_role_binding.yaml
  config/rbac/csi_rbd_provisioner_service_account.yaml
  config/rbac/kustomization.yaml
Labels: size/XL, lgtm, approved
