Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-06, with the labels that each got.

#354 DFBUGS-2366: [release-4.16] restrict manager to watch selective namespaces
  main.go
  pkg/utils/k8sutils.go
Labels: size/S, lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical

#382 controllers: delete StorageClaims post upgrade
  config/rbac/role.yaml
  internal/controller/maintenancemode_controller.go
  internal/controller/storageclient_controller.go
Labels: size/M, lgtm, approved

#391 ci: fix the paths in verify-generated action
  .github/workflows/verify-generated.yaml
Labels: size/XS, lgtm, approved

#396 controllers: verify kind before deletion of StorageClaim
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#395 csi: add secondary name check for ex-snapshotter
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
Labels: size/S, lgtm, approved

#406 Syncing latest changes from main for ocs-client-operator
  .github/workflows/verify-generated.yaml
  Makefile
  bundle/manifests/csi-images-v4.17
  bundle/manifests/csi-images-v4.18
  bundle/manifests/csi-images-v4.19
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  go.mod
  go.sum
  hack/build-catalog.sh
  hack/create-csi-images-manifest.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#410 controllers: reinstate noobaa to reconcile list
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#415 controllers: remove noobaa subscription if already present
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
Labels: size/L, lgtm, approved
