Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-07, with the labels that each got.

#427 DFBUGS-2711:[release-4.18] Revert remove of noobaa from client cluster
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#428 controllers: add watches for noobaa and remove reconciliation
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#431 DFBUGS-2640:[release-4.19] controllers: add watches for noobaa and remove reconciliation
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#434 controllers: manage webhook only if we are running standalone
  internal/controller/operatorconfigmap_controller.go
Labels: size/M, lgtm, approved

#386 controllers: reconcile vgrc sent by the provider
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#433 Syncing latest changes from main for ocs-client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved

#437 controllers: fix reconciliation message with hub sent reason
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#438 set default limits/requests for csi pods
  pkg/templates/csi.go
Labels: size/L, lgtm, approved

#443 controllers: reverting check for driverSpecDefaults
  internal/controller/operatorconfigmap_controller.go
Labels: size/XS, lgtm
