Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-02, with the labels that each got.

#298 Syncing latest changes from main for ocs-client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclaim_controller.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/ramendr/ramen/api/v1alpha1/drpolicy_types.go
  vendor/github.com/ramendr/ramen/api/v1alpha1/volumereplicationgroup_types.go
  vendor/github.com/ramendr/ramen/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#299 controllers: trigger reconcile for claims when the desired hash changes
  internal/controller/storageclaim_controller.go
Labels: size/S, lgtm, approved

#303 Syncing latest changes from main for ocs-client-operator
  internal/controller/storageclaim_controller.go
Labels: size/S, lgtm, approved

#304 controllers: update maintenance mode controller
  internal/controller/maintenancemode_controller.go
Labels: size/M, lgtm, approved

#307 Syncing latest changes from main for ocs-client-operator
  internal/controller/maintenancemode_controller.go
Labels: size/M, lgtm, approved

#309 controllers: skip checking for vgsc if the crd is not present
  internal/controller/storageclaim_controller.go
Labels: size/XS, lgtm, approved
