Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-05, with the labels that each got.

#359 controllers: query the csvname based on operator deployment owner
  cmd/main.go
  internal/controller/storageclient_controller.go
  pkg/utils/k8sutils.go
  service/status-report/main.go
Labels: size/L, lgtm, approved

#365 upgrade noobaa along with client-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/operatorconfigmap_controller.go
  pkg/utils/subscription.go
Labels: size/M, lgtm, approved

#355 controllers: stop calling GetStorageConfig from status reporter
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/status-reporter-clusterrole.yaml
  service/status-report/main.go
Labels: size/M, lgtm, approved

#362 controllers: don't replace the obj if it can be updated
  internal/controller/storageclient_controller.go
  pkg/utils/k8sutils.go
Labels: size/L, lgtm, approved

#371 Avoid updating empty channel on the storage client annotations
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#374 controllers: update missing permissions for classes
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#348 DFBUGS-2326: [release-4.18] bundle: add recipe op as a dependency
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
Labels: size/M, lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-critical
