Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-09, with the labels that each got.

#460 controllers: remove deprecated code for 4.20
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/crd/bases/ocs.openshift.io_storageclaims.yaml
  config/rbac/role.yaml
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved

#463 controllers: reconcile the resources by GK instead of GVK
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#464 DFBUGS-3996: [release-4.20] controllers: remove deprecated code for 4.20
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/crd/bases/ocs.openshift.io_storageclaims.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved, jira/valid-bug, jira/valid-reference

#472 Use lower cpu, memory requests for csi sidecars
  pkg/templates/csi.go
Labels: size/S, lgtm, approved
