Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-03, with the labels that each got.

#312 bundle: update versions
  Makefile
  bundle/manifests/csi-images-v4.18
  bundle/manifests/csi-images-v4.19
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/make-bundle-vars.mk
Labels: size/M, lgtm, approved

#313 console: add S3 proxy service declaration
  pkg/console/console.go
Labels: size/S, lgtm, approved

#315 controllers: update csi-op subscription based on provider version
  internal/controller/operatorconfigmap_controller.go
Labels: size/S, lgtm, approved

#318 ci: refactor and fix gitignore & make targets
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/dispatch-image-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/lint-and-spellcheck.yaml
  .github/workflows/operator-build-pipeline.yaml
  .github/workflows/verify-generated.yaml
  .github/workflows/yamllint.yaml
  .gitignore
  .golangci.yaml
  Makefile
  hack/godeps-verify.sh
  vendor/golang.org/x/text/message/catalog/catalog.go
  vendor/golang.org/x/text/message/catalog/dict.go
  vendor/golang.org/x/text/message/catalog/go19.go
  vendor/golang.org/x/text/message/catalog/gopre19.go
Labels: size/L, lgtm, approved

#301 remove the init container that decides the allowing of reconciliation of manager
  Dockerfile
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  hack/go-build.sh
  internal/controller/operatorconfigmap_controller.go
  service/deployment-guard/main.go
Labels: size/L, lgtm, approved

#322 controllers: remove ack step from storageclient onboarding
  internal/controller/storageclient_controller.go
Labels: size/M, lgtm, approved

#302 remove storageclaim api and corresponding controller along with references
  PROJECT
  api/v1alpha1/storageclaim_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/manifests/ocs.openshift.io_storageclaims.yaml
  cmd/main.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storageclaims.yaml
  config/crd/patches/webhook_in_storageclaims.yaml
  config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/storageclaim_editor_role.yaml
  config/rbac/storageclaim_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/ocs_v1alpha1_storageclaim.yaml
  internal/controller/maintenancemode_controller.go
  internal/controller/operatorconfigmap_controller.go
  internal/controller/storageclaim_controller.go
  internal/controller/storageclient_controller.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclaim_types.go
  vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#324 controllers: always enable nfs csi driver
  internal/controller/operatorconfigmap_controller.go
  pkg/templates/csi.go
Labels: size/S, lgtm, approved

#325 controllers: reconcile a single request in isolation with other requests
  go.mod
  internal/controller/storageclient_controller.go
  pkg/utils/events.go
Labels: size/L, lgtm, approved

#326 controllers: add dynamic watches for volumesnapshotclass
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved

#327 controllers: reconcile resources that will be part of GetStorageConfig
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved

#330 controllers: fix clientProfile and cephConnection
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#331 controllers: use map[string][]byte to unmarsahll secrets
  internal/controller/storageclient_controller.go
Labels: size/XS, lgtm, approved

#332 controllers: update secret data with received resource
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved
