Repository red-hat-storage/ocs-client-operator, pull requests merged in 2025-04, with the labels that each got.

#333 bundle: remove optional mount for nginx-configmap
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
Labels: size/XS, lgtm, approved

#334 controllers: fix ensureClusterScopedResources
  internal/controller/storageclient_controller.go
Labels: size/S, lgtm, approved

#321 Syncing latest changes from main for ocs-client-operator
  Dockerfile
  Makefile
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  hack/go-build.sh
  internal/controller/operatorconfigmap_controller.go
  service/deployment-guard/main.go
Labels: size/L, lgtm, approved

#335 sync between csi deletion by rook and csi creation by csi-operator
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/operatorconfigmap_controller.go
Labels: size/M, approved

#336 controllers: set csidriver.spec.seLinuxMount to true
  pkg/templates/csi.go
Labels: size/XS, lgtm, approved

#337 godeps: pull latest ocs-op changes
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/client/client.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider.pb.go
  vendor/github.com/red-hat-storage/ocs-operator/services/provider/api/v4/provider_grpc.pb.go
  vendor/golang.org/x/text/internal/number/format.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#341 Updated golang.org/x/oauth2 version from v0.24.0 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#338 controllers: use GetDesiredClientState instead of GetStorageConfig
  internal/controller/storageclient_controller.go
Labels: size/L, lgtm, approved

#339 controllers: read subscription channel from GetDesiredClientState rpc
  internal/controller/storageclient_controller.go
  service/status-report/main.go
Labels: size/S, lgtm, approved

#342 Syncing latest changes from main for ocs-client-operator
  go.mod
  go.sum
  internal/controller/storageclient_controller.go
  service/status-report/main.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#343 DFBUGS-1949: [release-4.18] upgrade dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/sys/unix/README.md
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/vgetrandom_linux.go
  vendor/golang.org/x/sys/unix/vgetrandom_unsupported.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: size/S, lgtm, approved, jira/valid-bug, jira/valid-reference

#345 bundle: add recipe op as a dependency
  bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/metadata/dependencies.yaml
  hack/build-catalog.sh
  hack/make-bundle-vars.mk
  internal/controller/operatorconfigmap_controller.go
Labels: size/M, lgtm, approved

#346 controllers: disable csi ctrlPlugin hostNetwork for internal client
  internal/controller/operatorconfigmap_controller.go
  pkg/templates/csi.go
Labels: size/S, lgtm, approved

#349 restrict manager to watch selective namespaces
  cmd/main.go
  pkg/utils/k8sutils.go
Labels: size/S, lgtm, approved
